config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'intro_pages#index'
  get 'privacy', to: 'intro_pages#privacy'
  get 'careers', to: 'intro_pages#careers'
  get 'team', to: 'intro_pages#team'
  resources :coaches, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :tutorials, only:[:index, :show] do
    resources :enrollments, only: :create
  end
  resources :chapters, only: [:show]
  namespace :coach do
    resources :sections, only:[] do
      resources :chapters, only: [:new, :create]
    end
    resources :tutorials, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
      resources :coaches, only: [:new, :create, :show] do
    end
  end
  resources :users, only: :show
end

app/models/coach.rb
class Coach < ApplicationRecord

  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :bio, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

 
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/controllers/coach/chapters_controller.rb
class Coach::ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section


  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = @current_section.chapters.create(chapter_params)
    redirect_to coach_tutorial_path(current_section.tutorial)
  end

  private

  def require_authorized_for_current_section
    if current_section.tutorial.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end


  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def chapter_params
    params.require(:chapter).permit(:title, :subtitle, :video)
  end
end

app/controllers/coach/coaches_controller.rb
class Coach::CoachesController < ApplicationController
  before_action :authenticate_user!

  def new
    @coach = Coach.new
  end

  def create
    @coach = current_user.coaches.create(coach_params)
    if @coach.valid?
      redirect_to coach_coach_path(@coach)
    else
      render :new, status: :unprocessble_entity
    end
  end

  def show
    @coach = Coach.find(params[:id])
  end

  private

  def coach_params
    params.require(:coach).permit(:name, :bio, :System_type, :description, :cost)
  end
    
end

app/controllers/coach/sections_controller.rb
class Coach::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_tutorial

  def new
    @section = Section.new
  end

  def create
    @section = @current_tutorial.sections.create(section_params)
    redirect_to coach_tutorial_path(current_tutorial)
  end

  private

  def require_authorized_for_current_tutorial
    if current_tutorial.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_tutorial
  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:tutorial_id])
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/controllers/coach/tutorials_controller.rb
class Coach::TutorialsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_tutorial, only: [:show]

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = current_user.tutorials.create(tutorial_params)
    if @tutorial.valid?
      redirect_to coach_tutorial_path(@tutorial)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    
  end

  private

  def require_authorized_for_current_tutorial
    if current_tutorial.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_tutorial
  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:id])
  end

  def tutorial_params
    params.require(:tutorial).permit(:title, :System_type, :description, :cost, :image)
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coach = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorial =Tutorial.all
  end

  def show
   @tutorial = Tutorial.find(params[:id])
  end
end

app/helpers/coach/chapters_helper.rb
module Coach::ChaptersHelper
end

app/helpers/coach/coaches_helper.rb
module Coach::CoachesHelper
end

app/helpers/coach/sections_helper.rb
module Coach::SectionsHelper
end

app/helpers/coach/tutorials_helper.rb
module Coach::TutorialsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/coach/tutorials/new.html.erb
<br />
<br />
<br />
<br />
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center">Start a new tutorial</h1>
 
   <%= simple_form_for @tutorial, url: coach_tutorials_path do |f| %>
    <%= f.input :title %>
    <%= f.select :System_type, ['Apple', 'Android'] %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: "btn btn-outline-secondary btn-sm" %>
    <br />
  <% end %>
  <br />
  <br />
  <br />
  <br />
</div>

app/views/coach/tutorials/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @current_tutorial.title %></h1>
    <%= image_tag current_tutorial.image.url.to_s, class: 'img-fluid' %>
  <br />
  <%= link_to 'Preview As Student', tutorial_path(current_tutorial), class: 'btn btn-warning float-right' %>
  <br class="clr" />

  <div class="text-center">
    <%= link_to 'Add a new section', new_coach_tutorial_section_path(current_tutorial), class: 'btn btn-primary btn-lg' %>
  </div>

  <ul>
    <% current_tutorial.sections.each do |section| %>
      <li>
        <%= section.title %>
        <%= link_to 'New Chapter', new_coach_section_chapter_path(section), class: 'float-right btn btn-primary btn-sm' %>
        <ul>
          <% section.chapters.each do |chapter| %></b>
            <li>
              <b><%= chapter.title %></b>
              -
              <%= chapter.subtitle %>
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>