config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'intro_pages#index'
  get 'privacy', to: 'intro_pages#privacy'
  get 'careers', to: 'intro_pages#careers'
  get 'team', to: 'intro_pages#team'
  resources :coaches, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :tutorials, only:[:index, :show] do
    resources :enrollments, only: :create
  end
  resources :chapters, only: [:show]
  namespace :coach do
    resources :sections, only:[] do
      resources :chapters, only: [:new, :create]
    end
    resources :tutorials, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
      resources :coaches, only: [:new, :create, :show] do
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader
end

app/models/coach.rb
class Coach < ApplicationRecord

  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :bio, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :coach

   RATINGS = {
    'one star': '*',
    'two stars': '**',
    'three stars': '***',
    'four stars': '****',
    'five stars': '*****'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :tutorial
  belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :tutorial
  has_many :chapters
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/user.rb
class User < ApplicationRecord
 mount_uploader :avatar, AvatarUploader
 
  
  has_many :coaches
  has_many :comments
  has_many :tutorials
  has_many :enrollments
  has_many :enrolled_tutorials, through: :enrollments, source: :tutorial
  has_one_attached :avatar
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(tutorial)
    return enrolled_tutorials.include?(tutorial)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 
  
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_chapter, only:[:show]


  def show
  end

  private

  def require_authorized_for_current_chapter
    unless current_user.enrolled_in?(current_chapter.section.tutorial)
      redirect_to tutorial_url(current_chapter.section.tutorial), alert: "You must enroll in the course to view this Chapter"
    end
  end

  helper_method :current_chapter
  def current_chapter
    @current_chapter ||= Chapter.find(params[:id])
  end
end

app/controllers/coach/tutorials_controller.rb
class Coach::TutorialsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_tutorial, only: [:show]

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = current_user.tutorials.create(tutorial_params)
    if @tutorial.valid?
      redirect_to coach_tutorial_path(@tutorial)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    
  end

  private

  def require_authorized_for_current_tutorial
    if current_tutorial.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_tutorial
  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:id])
  end

  def tutorial_params
    params.require(:tutorial).permit(:title, :System_type, :description, :cost, :image)
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coach = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @coach = Coach.find(params[:coach_id])
    @coach.comments.create(comment_params.merge(user: current_user))
    redirect_to coach_path(@coach)
  end

   private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_tutorial.premium?
      # Amount in cents
      @amount = (current_tutorial.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'easilysmart Content',
        currency: 'usd'
      )
    end

  current_user.enrollments.create(tutorial: current_tutorial)
  redirect_to tutorial_path(current_tutorial) 
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:tutorial_id])
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorial =Tutorial.all
  end

  def show
   @tutorial = Tutorial.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  private

   def user_params
    params.permit(:avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/coach/tutorials_helper.rb
module Coach::TutorialsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/intro_pages_helper.rb
module IntroPagesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tutorials/index.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">From basic to smart</h1>

  <hr />

  <% @tutorial.each do |tutorial| %>
    <div class="card col-4 offset-4">
      <h2 class="handle">
        <%=link_to tutorial.title, tutorial_path(tutorial) %></h2>
        <%= image_tag tutorial.image.url.to_s, class: 'img-fluid' %>

      <h5 class="gram-actions float-right">
        <br class="clear-fix" />
        <%= tutorial.System_type %>
      </h5>
      <br />
      <div class="row">
        <div class="col-sm-8 col-12">
          <%= tutorial.description %>
        </div>
        <div class="col-sm-4 col-12 text-center">
          <%= link_to 'Learn', tutorial_path(tutorial), class: 'btn btn-dark btn-sm' %>
        </div>
      </div>
      <br class="clr" />
    </div>
  <% end %>
</div>

app/views/tutorials/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @tutorial.title %></h1>
    <%= image_tag @tutorial.image.url, class: 'img-fluid' %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <h5><%= @tutorial.System_type %></h5>
  
      <div class="col-sm-8 col-12">
        <span class="badge badge-default">
          <%= number_to_currency @tutorial.cost %>
        </span>

      <% if current_user && current_user == @tutorial.user %>
        <br />
        <br />
        <%= link_to 'Administer', coach_tutorial_path(@tutorial), class: 'btn btn-danger btn-large' %>
      <% end %>

      <br />
      <br />

      <% if current_user %>
        <% if current_user && current_user.enrolled_in?(@tutorial) %>
          <h3 class="badge badge-info">You Are Enrolled!</h3>
        <% else %>
          <% if @tutorial.free? %>
            <%= link_to 'Enroll', tutorial_enrollments_path(@tutorial), class: 'btn btn-primary', method: :post %>
          <% else %>
            <%= form_tag tutorial_enrollments_path(@tutorial) do %>


              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-email="<%= current_user.email %>"
                  data-description="<%= @tutorial.title %> (<%= number_to_currency @tutorial.cost %>)"
                  data-amount="<%= (@tutorial.cost * 100).to_i %>"
                  data-locale="auto"></script>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <h3 class="badge badge-info"> Sign In to Enroll! </h3>
      <% end %>
    </div>
    <div class="col-sm-8 col-12">
      <%= @tutorial.description %>
    </div>
  </div>
  <div class="col-12">
    <% @tutorial.sections.each do |section| %>
    <br /><br />
      <div class="section">
        <h3>
          <%= section.title %>  
        </h3>
        <div class="row">
          <% section.chapters.each do |chapter| %>
            <div class="col-12 col-sm-6">
              <div class="chapter text-center">
                <br />
                <%= link_to chapter_path(chapter) do %>
                  <b><%= chapter.title %></b>
                  <br />
                  <%= chapter.subtitle %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <br class="clr" />
      </div>
    <% end %>
  </div>
</div>