config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'intro_pages#index'
  get 'privacy', to: 'intro_pages#privacy'
  get 'careers', to: 'intro_pages#careers'
  get 'team', to: 'intro_pages#team'
  resources :coaches, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :tutorials, only:[:index, :show] do
    resources :enrollments, only: :create
  end
  resources :chapters, only: [:show]
  namespace :coach do
    resources :sections, only:[] do
      resources :chapters, only: [:new, :create]
    end
    resources :tutorials, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
      resources :coaches, only: [:new, :create, :show] do
    end
  end
  resources :users, only: :show
end

app/models/coach.rb
class Coach < ApplicationRecord

  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :bio, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

 
end

app/controllers/coach/chapters_controller.rb
class Coach::ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section


  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = @current_section.chapters.create(chapter_params)
    redirect_to coach_tutorial_path(current_section.tutorial)
  end

  private

  def require_authorized_for_current_section
    if current_section.tutorial.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end


  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def chapter_params
    params.require(:chapter).permit(:title, :subtitle, :video)
  end
end

app/controllers/coach/coaches_controller.rb
class Coach::CoachesController < ApplicationController
  before_action :authenticate_user!

  def new
    @coach = Coach.new
  end

  def create
    @coach = current_user.coaches.create(coach_params)
    if @coach.valid?
      redirect_to coach_coach_path(@coach)
    else
      render :new, status: :unprocessble_entity
    end
  end

  def show
    @coach = Coach.find(params[:id])
  end

  private

  def coach_params
    params.require(:coach).permit(:name, :bio, :System_type, :description, :cost)
  end
    
end

app/controllers/coach/sections_controller.rb
class Coach::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_tutorial

  def new
    @section = Section.new
  end

  def create
    @section = @current_tutorial.sections.create(section_params)
    redirect_to coach_tutorial_path(current_tutorial)
  end

  private

  def require_authorized_for_current_tutorial
    if current_tutorial.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_tutorial
  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:tutorial_id])
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/controllers/coach/tutorials_controller.rb
class Coach::TutorialsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_tutorial, only: [:show]

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = current_user.tutorials.create(tutorial_params)
    if @tutorial.valid?
      redirect_to coach_tutorial_path(@tutorial)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    
  end

  private

  def require_authorized_for_current_tutorial
    if current_tutorial.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_tutorial
  def current_tutorial
    @current_tutorial ||= Tutorial.find(params[:id])
  end

  def tutorial_params
    params.require(:tutorial).permit(:title, :System_type, :description, :cost, :image)
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coach = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/coach/chapters_helper.rb
module Coach::ChaptersHelper
end

app/helpers/coach/coaches_helper.rb
module Coach::CoachesHelper
end

app/helpers/coach/sections_helper.rb
module Coach::SectionsHelper
end

app/helpers/coach/tutorials_helper.rb
module Coach::TutorialsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/index.html.erb
<br />

<div class="col-6 offset-2 col-sm-4 offset-sm-2 col-md-5 offset-md-3">
  <h1 class="text-center">Find your Coach</h1>
  <br />

   <% @coach.each do |coach| %>
     <div class="card">
      <h2 class="handle">
        <%= link_to coach.name, coach_path(coach) %>   
      </h2>
      <br />
      <div class="row">
        <div class="col-sm-8 col-12">
          
        </div>
        <div class="col-sm-8 col-16 text-center">
          <%= link_to 'Details', coach_path(coach), class: 'btn btn-dark btn-sm' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/coaches/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <div class="booyah-box col-sm-6">
    <h3><%= @coach.name %></h3>
    <br />
    <div class= "row">
      <div class="col-sm-12 col-18 text-left">
    
    
        <div class="float-left">
          <h5 class="float-left">bio:</h5>
          <br />
          <%= @coach.bio %>
        </div>

          <div class="float-left">
            <h5 class="float-left">Description:</h5>
            <br />
            <%= @coach.description %>
          </div>

        <div class="float-left">
          <h5 class="float-left">Per hour rate:</h5>
          <br />
          <span class="badge badge-default">
            <%= number_to_currency @coach.cost %>
          </span>
        </div>
        <%= form_tag coach_coach_path do %>
          

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="A month's subscription"
                  data-amount="500"
                  data-locale="auto"></script>
        <% end %>
      </div>
    </div>
  </div>
  <br />
  <br />
  <div class="booyah-box">
    <div class="col-10 offset-1">
      <h1 class="float-left">Comments</h1>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-outline-secondary btn-sm float-right" data-toggle="modal" data-target="#myModal">
        Add a comment
      </button>
    </div>

    <div class="clear"></div>
    <div class="row">
      <% @coach.comments.each do |comment| %>
        <div class="col-12 col-sm-6">
          <blockquote>
            <% if comment.humanized_rating.present? %>
              <b><%= comment.humanized_rating %></b> -
            <% end %>
            <%= comment.message %>
            <small><%= comment.user.email %></small>
          </blockquote>
        </div>
      <% end %>
    </div>
  </div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @comment, url: coach_comments_path(@coach) do |f| %>
          <div class="modal-footer">
            <%= f.input :message %>
            <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", class: "btn btn-outline-secondary btn-sm float-right" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>