config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'intro_pages#index'
  get 'privacy', to: 'intro_pages#privacy'
  get 'careers', to: 'intro_pages#careers'
  get 'team', to: 'intro_pages#team'
  resources :coaches, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :tutorials, only:[:index, :show] do
    resources :enrollments, only: :create
  end
  resources :chapters, only: [:show]
  namespace :coach do
    resources :sections, only:[] do
      resources :chapters, only: [:new, :create]
    end
    resources :tutorials, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
      resources :coaches, only: [:new, :create, :show] do
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader
end

app/models/coach.rb
class Coach < ApplicationRecord

  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :bio, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :coach

   RATINGS = {
    'one star': '*',
    'two stars': '**',
    'three stars': '***',
    'four stars': '****',
    'five stars': '*****'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :tutorial
  belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :tutorial
  has_many :chapters
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :System_type, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/user.rb
class User < ApplicationRecord
 mount_uploader :avatar, AvatarUploader
 
  
  has_many :coaches
  has_many :comments
  has_many :tutorials
  has_many :enrollments
  has_many :enrolled_tutorials, through: :enrollments, source: :tutorial
  has_one_attached :avatar
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(tutorial)
    return enrolled_tutorials.include?(tutorial)
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_chapter, only:[:show]


  def show
  end

  private

  def require_authorized_for_current_chapter
    unless current_user.enrolled_in?(current_chapter.section.tutorial)
      redirect_to tutorial_url(current_chapter.section.tutorial), alert: "You must enroll in the course to view this Chapter"
    end
  end

  helper_method :current_chapter
  def current_chapter
    @current_chapter ||= Chapter.find(params[:id])
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coach = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @coach = Coach.find(params[:coach_id])
    @coach.comments.create(comment_params.merge(user: current_user))
    redirect_to coach_path(@coach)
  end

   private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  private

   def user_params
    params.permit(:avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/intro_pages_helper.rb
module IntroPagesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easilysmart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates&display=swap" rel="stylesheet">
    <link href="http://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
  </head>
  <body>

<div id="flex-content-container">
<nav class="navbar navbar-fixed-top navbar-expand-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <a class="navbar-brand" href="/">easilySmart</a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tutorials
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to 'Android', tutorials_path, class: 'nav-link' %>
            <a class="dropdown-item">
              <%= link_to 'Apple', tutorials_path, class: 'nav-link' %>
            
        </div>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Create
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to 'Android', new_coach_tutorial_path("andriod"), class: 'nav-link' %>
            <a class="dropdown-item">
              <%= link_to 'Apple', new_coach_tutorial_path, class: 'nav-link' %>
            
        </div>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Find your Coach
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to 'Android', coaches_path, class: 'nav-link' %>
            <a class="dropdown-item">
              <%= link_to 'Apple', coaches_path, class: 'nav-link' %>
            
        </div>
      </li>
    </ul>
    <ul class="navbar-nav col-12 offset-4 col-sm-4">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
</div>

    <footer>
      <div class="container">
        
         <br />
          <%= link_to 'create a Tutorial', new_coach_tutorial_path %>
          <br />
          <%= link_to 'Become a coach', new_coach_coach_path %>
      </div>
      
    </footer>>

    <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

 
    
  </body>
</html>




 